Feature/lib 34
NoName-ForTeam/ui-lib pull request #30
Opened 2024-08-24 17:21 UTC by Lelik7777

# Pagination Component Implementation

## Changes
This PR introduces a new pagination component with the following features:

1. Custom pagination hook (`usePagination`) for handling pagination logic
2. Reusable `Pagination` component with customizable page size and navigation
3. `PaginationButton` component for individual page buttons
4. `SelectContainer` for page size selection
5. Storybook stories showcasing default and select-enabled pagination

Additionally, this PR includes some project maintenance:
- Removed the Vite config timestamp file

## Implementation Details
- The `usePagination` hook calculates the pagination range and provides navigation functions
- The `Pagination` component uses the hook to render a fully functional pagination UI
- `PaginationButton` is used for individual page numbers and navigation buttons
- `SelectContainer` allows users to change the number of items per page
- Storybook stories demonstrate the component's usage and variations

## Testing
- Storybook stories have been added to showcase and test the component's functionality
- Manual testing has been performed to ensure correct behavior in various scenarios

## Notes for Reviewers
- Please pay attention to the pagination logic in `usePagination` hook
- Check if the component is accessible and works well with keyboard navigation
- Verify that the Storybook stories cover all main use cases

## Screenshots
![Screenshot_3](https://github.com/user-attachments/assets/58516a3b-0a32-46fb-9f83-2b5396552e9a)

2024-08-25 18:09 UTC, NoName-ForTeam requested changes

2024-08-25 18:09 UTC, NoName-ForTeam commented on src/components/ui/pagination/pagination.tsx
> +  const classNames = { container: styles.container, root: styles.root } as const
думаю, нужно добавить className и ...rest для главного контейнера

2024-08-26 07:22 UTC, Lelik7777 commented on src/components/ui/pagination/pagination.tsx
> +  const classNames = { container: styles.container, root: styles.root } as const
добавил и исправил

2024-08-26 16:29 UTC, EvgeniyaYakunina approved these changes

2024-08-26 17:00 UTC, merged